version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" # Exposed so you can inspect with redis-cli locally
    networks:
      - task-net

  api-service:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - task-net

  worker-service:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_MAX_ATTEMPTS=3
    depends_on:
      - redis
    deploy:
      replicas: 2 # Let's run 2 workers to prove concurrency!
    networks:
      - task-net

networks:
  task-net:
    driver: bridge